### ISSUE TITLE
Expected REPL Connections Evaporated!

### ISSUE THREAD

**Issue by jleonard-r7** [bhauman/figwheel-repl#16]
Wouldn't it be possible to attempt to create more connections / a new connection when this happens?

Here's the log:

```
2021-03-10 19:36:09.435:INFO::main: Logging initialized @4612ms to org.eclipse.jetty.util.log.StdErrLog
[Figwheel] Validating figwheel-main.edn
[Figwheel] figwheel-main.edn is valid \(ツ)/
[Figwheel] Compiling build test to "target/public/cljs-out/test-main.js"
[Figwheel] Successfully compiled build test to "target/public/cljs-out/test-main.js" in 3.202 seconds.
Launching Javascript environment with script:  "./scripts/launch_headless.sh"
Environment output being logged to: target/public/cljs-out/test/js-environment.log
Expected REPL Connections Evaporated!
No stacktrace available.
Execution error (ExceptionInfo) at cljs.repl/evaluate-form (repl.cljc:578).
Expected REPL Connections Evaporated!
```

**Comment by jleonard-r7** [comment]
Is this being looked at?

**Comment by bhauman** [comment]
I'm finally taking a look at this. Thanks for the ping

**Comment by bhlieberman** [comment]
I also received this error seemingly as a result of trying to modify my `figwheel-main.edn`. I was getting timeouts in the REPL so I added the `:repl-eval-timeout` key to the map and set it to 15000. When I started the REPL with `cider-jack-in-cljs` it started the REPL but said it could not include `cljs.core` and defaulted to a regular Clojure REPL. So I tried to do it outside of Emacs/Cider with `lein fig:build` and got ```clj
Exception in thread "main" Syntax error compiling at (/tmp/form-init16178072584464894618.clj:1:74).
Unexpected error during REPL initialization
        at clojure.lang.Compiler.load(Compiler.java:7647)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Unexpected error during REPL initialization {:cljs.repl/error :init-failed}
        at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:1220)
        at cljs.repl$repl_STAR_.invoke(repl.cljc:1033)
        at rebel_readline.cljs.repl$eval10574$repl_STAR___10575.invoke(repl.clj:77)
        at clojure.lang.Var.invoke(Var.java:388)
        at figwheel.main$repl.invokeStatic(main.cljc:1916)
        at figwheel.main$repl.invoke(main.cljc:1873)
        at figwheel.main$repl_action.invokeStatic(main.cljc:1928)
        at figwheel.main$repl_action.invoke(main.cljc:1923)
        at figwheel.main$default_compile.invokeStatic(main.cljc:2216)
        at figwheel.main$default_compile.invoke(main.cljc:2167)
        at figwheel.main$build_main_opt.invokeStatic(main.cljc:650)
        at figwheel.main$build_main_opt.invoke(main.cljc:645)
        at cljs.cli$main.invokeStatic(cli.clj:703)
        at cljs.cli$main.doInvoke(cli.clj:692)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at cljs.main$_main.invokeStatic(main.clj:65)
        at cljs.main$_main.doInvoke(main.clj:56)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at figwheel.main$_main$fn__8472.invoke(main.cljc:2554)
        at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
        at clojure.core$with_redefs_fn.invoke(core.clj:7498)
        at figwheel.main$_main.invokeStatic(main.cljc:2552)
        at figwheel.main$_main.doInvoke(main.cljc:2530)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:393)
        at user$eval140.invokeStatic(form-init16178072584464894618.clj:1)
        at user$eval140.invoke(form-init16178072584464894618.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        ... 12 more
Caused by: clojure.lang.ExceptionInfo: Expected REPL Connections Evaporated! {:type :js-eval-exception, :error {:status :exception, :value "Expected REPL Connections Evaporated!", :stacktrace "No stacktrace available."}, :repl-env #figwheel.repl.FigwheelReplEnv{:output-dir "resources/public/cljs-out/dev", :bound-printer #object[clojure.lang.Atom 0x5daf5ea5 {:status :ready, :val #object[clojure.core$bound_fn_STAR_$fn__5734 0x21727e54 "clojure.core$bound_fn_STAR_$fn__5734@21727e54"]}], :repl-eval-timeout 15000, :broadcast false, :out-print-fn nil, :server #object[clojure.lang.Atom 0x2ec173e5 {:status :ready, :val nil}], :port 9500, :output-to "resources/public/cljs-out/dev/main_bundle.js", :focus-session-name #object[clojure.lang.Atom 0x21fdc052 {:status :ready, :val nil}], :err-print-fn nil, :node-proc #object[clojure.lang.Atom 0x600e8be {:status :ready, :val nil}], :ring-stack-options {:figwheel.server.ring/dev {:figwheel.server.ring/system-app-handler #object[figwheel.main$add_default_system_app_handler$fn__8262$fn__8263 0x71faeb31 "figwheel.main$add_default_system_app_handler$fn__8262$fn__8263@71faeb31"]}}, :print-to-output-streams true, :printing-listener #object[clojure.lang.Atom 0x34b2a6f4 {:status :ready, :val #object[clojure.core$bound_fn_STAR_$fn__5734 0x1149b5dc "clojure.core$bound_fn_STAR_$fn__5734@1149b5dc"]}], :target :bundle, :open-url "http://[[server-hostname]]:[[server-port]]", :connection-filter #object[figwheel.main$config_repl_connect$fn__7974 0x50e31126 "figwheel.main$config_repl_connect$fn__7974@50e31126"]}, :form (set! cljs.core/*print-namespace-maps* true), :js "(cljs.core._STAR_print_namespace_maps_STAR_ = true)"}
        at cljs.repl$evaluate_form.invokeStatic(repl.cljc:577)
        at cljs.repl$evaluate_form.invoke(repl.cljc:498)
        at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:1129)
        ... 45 more```
